version: '3.8'

services:

#  nginx:
#    build: ./nginx
#    volumes:
#      - dp_test_static_files:/src/web/static
#    ports:
#      - "80:80"
#    networks:
#      app-tier:
#    depends_on:
#      - web
#
#  web:
#    volumes:
#      - dp_test_static_files:/src/web/static
#    build: ./src
#    command: run_server
#    env_file:
#      - env/local
#    expose:
#      - 6660
#    networks:
#      app-tier:

  server:
    build: ./monitoring
    ports:
      - "6666:6666"
#
#  zookeeper:
#    image: wurstmeister/zookeeper
#    ports:
#      - "2181:2181"
#    logging:
#      driver: none
#
#  kafka:
#    image: wurstmeister/kafka:latest
#    ports:
#      - target: 9094
#        published: 9094
#        protocol: tcp
#        mode: host
#    env_file:
#      - env/local
#    environment:
#      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
#      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
#      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
#      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
#      KAFKA_CREATE_TOPICS: "topic.test_a:1:1,topic.test_b:1:1"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    logging:
#      driver: none

#
#  redis:
#    image: redis
#    expose:
#      - 6379
#
#  test:
#    volumes:
#      - static:/src/web/static
#    build: ./src
#    command: run_tests
#    env_file:
#      - env/local
#    expose:
#      - 6660
#
#  worker:
#    build: ./src
#    command: run_celery_worker
#    links:
#      - redis
#    depends_on:
#      - redis


volumes:
  dp_test_static_files:
networks:
  app-tier:
    driver: bridge