version: '3.8'

services:

  server:
    build: .
    ports:
      - "6666:6666"

#  zookeeper:
#    image: wurstmeister/zookeeper
#    ports:
#      - "2181:2181"
#    logging:
#      driver: none
#
#  kafka:
#    image: wurstmeister/kafka:latest
#    ports:
#      - target: 9094
#        published: 9094
#        protocol: tcp
#        mode: host
#    env_file:
#      - env/local
#    environment:
#      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
#      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
#      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
#      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
#      KAFKA_CREATE_TOPICS: "${KAFKA_TOPICS}"
#      KAFKA_CREATE_TOPICS_SEPARATOR: "$$'\n'"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    logging:
#      driver: none
